In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris=load_iris()
X=iris["data"][:,2:]
y=(iris["target"]==2).astype(np.int)

<ipython-input-1-505f69e50a0c>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y=(iris["target"]==2).astype(np.int)


In [2]:
from sklearn.cluster import KMeans
k=5
kmeans=KMeans(n_clusters=5)
y_pred=kmeans.fit_predict(X)
X[:4]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2]])

In [3]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 4, 0, 0, 0, 4, 0, 4, 4, 0, 4, 0, 4, 0,
       0, 4, 0, 4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 0, 0, 0, 0, 0,
       4, 4, 0, 0, 4, 4, 4, 4, 4, 0, 4, 4, 2, 3, 2, 3, 3, 2, 0, 2, 3, 2,
       3, 3, 3, 3, 3, 3, 3, 2, 2, 0, 3, 3, 2, 0, 3, 2, 0, 0, 3, 3, 2, 2,
       3, 0, 3, 2, 3, 3, 0, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3])

In [4]:
kmeans.cluster_centers_

array([[4.64857143, 1.5       ],
       [1.462     , 0.246     ],
       [6.28461538, 2.13846154],
       [5.39666667, 2.05333333],
       [3.83181818, 1.16818182]])

In [5]:
X_new=np.array([[0,2],[3,2],[6,3],[8,4]])

In [6]:
kmeans.predict(X_new)

array([1, 4, 2, 2])

In [7]:
kmeans.transform(X_new)

array([[4.67538408, 2.28340973, 6.28614048, 5.3969302 , 3.92106517],
       [1.72272684, 2.33280089, 3.28753248, 2.39726001, 1.17636855],
       [2.01899955, 5.30829163, 0.9073337 , 1.12258135, 2.83840981],
       [4.18115695, 7.53909544, 2.53137706, 3.25067002, 5.03914019]])

In [8]:
good_init=np.array([[-3,3],[-3,2],[-3,1],[-1,2],[0,2]])

In [9]:
kmeans=KMeans(n_clusters=5,init=good_init,n_init=1)

In [10]:
kmeans.fit(X)

KMeans(init=array([[-3,  3],
       [-3,  2],
       [-3,  1],
       [-1,  2],
       [ 0,  2]]),
       n_clusters=5, n_init=1)

In [11]:
kmeans.inertia_

14.701112010796223

In [12]:
from sklearn.cluster import MiniBatchKMeans

In [13]:
minibatch_kmeans=MiniBatchKMeans(n_clusters=5)

In [14]:
minibatch_kmeans.fit(X)

MiniBatchKMeans(n_clusters=5)

In [15]:
from sklearn.metrics import silhouette_score

In [16]:
silhouette_score(X,kmeans.labels_)

0.6011169787402741

In [17]:
from sklearn.datasets import load_digits
X_digits,y_digits=load_digits(return_X_y=True)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_digits,y_digits)

In [22]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression()
log_reg.fit(X_train,y_train)

E:\User\My_Playground\envs\tensorflowGPU\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [23]:
log_reg.score(X_test,y_test)

0.9555555555555556

In [24]:
n_labeled=50
log_reg=LogisticRegression()
log_reg.fit(X_train[:n_labeled],y_train[:n_labeled])

E:\User\My_Playground\envs\tensorflowGPU\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [25]:
log_reg.score(X_test,y_test) 

0.8111111111111111

In [26]:
k=50
kmeans=KMeans(n_clusters=k)
X_digits_dist=kmeans.fit_transform(X_train)

In [28]:
X_digits_dist.shape

(1347, 50)

In [29]:
repre_digit_idex=np.argmax(X_digits_dist,axis=0)

In [32]:
repre_digit_idex

array([ 585, 1292,  539,  323,  788,  453, 1088,  197, 1041,  386,  886,
        886,  456,   31, 1340,  835,  681,  853,  886, 1140, 1292,  489,
         25,  323,  917,  231,  835,  489,  197,  872,   94,  472,  788,
        585,  197, 1189,  819,  197,  489,  872,  323,  853,  788,  774,
        323,  323,  389, 1292, 1143, 1140], dtype=int64)

In [34]:
X_repre_digits=X_train[repre_digit_idex]

In [37]:
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons 

In [41]:
X,y=make_moons(n_samples=1000,noise=0.005)

In [42]:
dbscan=DBSCAN(eps=0.05,min_samples=5)

In [44]:
dbscan.fit(X)

DBSCAN(eps=0.05)

In [45]:
dbscan.labels_

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,

In [50]:
from sklearn.mixture import GaussianMixture

In [51]:
gm=GaussianMixture(n_components=3,n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [52]:
gm.weights_

array([0.65781401, 0.17045839, 0.1717276 ])

In [53]:
gm.means_

array([[ 0.49843151,  0.25134916],
       [-0.81770694,  0.48594023],
       [ 1.81484246,  0.01046011]])

In [56]:
gm.covariances_.shape

(3, 2, 2)